### ISSUE TITLE
codecov-lite 

### ISSUE THREAD

**Issue by shellscape** [bubble-dev/_#173]
I'd like to request support in codecov-lite for `flags` as an option. See: https://docs.codecov.io/reference#upload for the flags definition. This is particularly useful for monorepos when sub-packages would like to track and display their individual coverage.

**Comment by deepsweet** [comment]
Hi.

Isn't it enough to set it up through `codecov.yml` like [here](https://docs.codecov.io/docs/flags#section-flags-example)?

```yml
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: null
      projectA:
        flags: projectA
        target: 90%
      projectB:
        target: 50%
        flags: projectB
flags:
  projectA:  
    paths:
      - projectA/src
  projectB:
    paths:
      - projectB/src
```
